In [1]:
import pandas as pd

# Working with JSON

In [2]:
df = pd.read_json("iris.json")

In [3]:
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

### Using URL

In [ ]:
pd.read_json("<url>")

# Working with sql

In [7]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in c:\users\luqma\appdata\local\programs\python\python310\lib\site-packages (2.2.9)

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import mysql.connector

In [12]:
con = mysql.connector.connect(host="localhost",user="root",password="",database="World")

In [18]:
pd.read_sql_query("SELECT * FROM city WHERE population > 10000000", con)

C:\Users\luqma\AppData\Local\Temp\ipykernel_87220\133419043.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE population > 10000000", con)

     ID             Name CountryCode     District  Population
0  1024  Mumbai (Bombay)         IND  Maharashtra    10500000