In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
a = 2

# storing the responce (ex: responce 200, 404, etc)

In [3]:
response = requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key=f8223b6e16ffdbd7d7ccf3577a2c765a&page={a}")

In [4]:
response.json()["results"]

[{'adult': False,
  'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
  'genre_ids': [18, 80],
  'id': 769,
  'title': 'GoodFellas',
  'original_language': 'en',
  'original_title': 'GoodFellas',
  'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
  'popularity': 23.8923,
  'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
  'release_date': '1990-09-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 14365},
 {'adult': False,
  'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
  'genre_ids': [28, 18],
  'id': 346,
  'title': 'Seven Samurai',
  'original_language': 'ja',
  'original_title': '七人の侍',
  'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
  'popularity': 15.6686,
  'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
  'release_date': '1954-04-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 4233},
 {'adult': False,
  'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg',
  'genre_ids': [16, 18, 10752],
  'id': 12477,
  'title': 'Grave of the Fireflies',
  'original_language': 'ja',
  'original_title': '火垂るの墓',
  'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
  'popularity': 0.0128,
  'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
  'release_date': '1988-04-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.4,
  'vote_count': 6522},
 {'adult': False,
  'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg',
  'genre_ids': [35, 18],
  'id': 637,
  'title': 'Life Is Beautiful',
  'original_language': 'it',
  'original_title': 'La vita è bella',
  'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
  'popularity': 13.8366,
  'poster_path': '/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg',
  'release_date': '1997-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.439,
  'vote_count': 13995},
 {'adult': False,
  'backdrop_path': '/xRyINp9KfMLVjRiO5nCsoRDdvvF.jpg',
  'genre_ids': [18, 53],
  'id': 550,
  'title': 'Fight Club',
  'original_language': 'en',
  'original_title': 'Fight Club',
  'overview': 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
  'popularity': 30.9548,
  'poster_path': '/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg',
  'release_date': '1999-10-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.438,
  'vote_count': 32067},
 {'adult': False,
  'backdrop_path': '/a0lfia8tk8ifkrve0Tn8wkISUvs.jpg',
  'genre_ids': [12, 14, 28],
  'id': 120,
  'title': 'The Lord of the Rings: The Fellowship of the Ring',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Fellowship of the Ring',
  'overview': 'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.',
  'popularity': 41.2906,
  'poster_path': '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
  'release_date': '2001-12-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.4,
  'vote_count': 27585},
 {'adult': False,
  'backdrop_path': '/e3hG3uadtcP0pYdRa5ch4ysQW76.jpg',
  'genre_ids': [28, 18, 36],
  'id': 14537,
  'title': 'Harakiri',
  'original_language': 'ja',
  'original_title': '切腹',
  'overview': 'Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.',
  'popularity': 10.0819,
  'poster_path': '/3nPwMd3KviJWaHzG9fZCqlwWMas.jpg',
  'release_date': '1962-09-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.432,
  'vote_count': 1210},
 {'adult': False,
  'backdrop_path': '/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg',
  'genre_ids': [18, 80],
  'id': 598,
  'title': 'City of God',
  'original_language': 'pt',
  'original_title': 'Cidade de Deus',
  'overview': 'In the poverty-stricken favelas of Rio de Janeiro in the 1970s, two young men choose different paths. Rocket is a budding photographer who documents the increasing drug-related violence of his neighborhood, while José “Zé” Pequeno is an ambitious drug dealer diving into a dangerous life of crime.',
  'popularity': 12.4734,
  'poster_path': '/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg',
  'release_date': '2002-08-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.429,
  'vote_count': 8189},
 {'adult': False,
  'backdrop_path': '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
  'genre_ids': [18, 10749],
  'id': 11216,
  'title': 'Cinema Paradiso',
  'original_language': 'it',
  'original_title': 'Nuovo Cinema Paradiso',
  'overview': "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
  'popularity': 11.4261,
  'poster_path': '/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg',
  'release_date': '1988-11-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.427,
  'vote_count': 4828},
 {'adult': False,
  'backdrop_path': '/kWYfW2Re0rUDE6IHhy4CRuKWeFr.jpg',
  'genre_ids': [12, 14, 28],
  'id': 121,
  'title': 'The Lord of the Rings: The Two Towers',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Two Towers',
  'overview': "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers--Orthanc Tower in Isengard, where the corrupt wizard Saruman awaits, and Sauron's fortress at Barad-dur, deep within the dark lands of Mordor. Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
  'popularity': 26.1014,
  'poster_path': '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
  'release_date': '2002-12-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.419,
  'vote_count': 23906},
 {'adult': False,
  'backdrop_path': '/mufF1aYvwdpKerhq5R1YrVcbJLY.jpg',
  'genre_ids': [27, 53, 9648],
  'id': 539,
  'title': 'Psycho',
  'original_language': 'en',
  'original_title': 'Psycho',
  'overview': 'When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.',
  'popularity': 18.4761,
  'poster_path': '/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg',
  'release_date': '1960-06-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.413,
  'vote_count': 10994},
 {'adult': False,
  'backdrop_path': '/6Oa3zTiluBz2W8D2ou1MY16dUiF.jpg',
  'genre_ids': [18],
  'id': 510,
  'title': "One Flew Over the Cuckoo's Nest",
  'original_language': 'en',
  'original_title': "One Flew Over the Cuckoo's Nest",
  'overview': 'A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.',
  'popularity': 13.7821,
  'poster_path': '/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg',
  'release_date': '1975-11-19',
  'softcore': False,
  'video': False,
  'vote_average': 8.413,
  'vote_count': 11458},
 {'adult': False,
  'backdrop_path': '/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg',
  'genre_ids': [35, 18, 14, 10749],
  'id': 40096,
  'title': "A Dog's Will",
  'original_language': 'pt',
  'original_title': 'O Auto da Compadecida',
  'overview': 'The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small town in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.',
  'popularity': 5.2383,
  'poster_path': '/z9Au9XtK0ARzkKGsZCzMkmKgMPf.jpg',
  'release_date': '2000-09-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.4,
  'vote_count': 1222},
 {'adult': False,
  'backdrop_path': '/4Nx40jwpoTHPjCWNGoaZ6kaoGxa.jpg',
  'genre_ids': [18],
  'id': 255709,
  'title': 'Hope',
  'original_language': 'ko',
  'original_title': '소원',
  'overview': 'After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.',
  'popularity': 14.8548,
  'poster_path': '/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg',
  'release_date': '2013-10-02',
  'softcore': False,
  'video': False,
  'vote_average': 8.398,
  'vote_count': 855},
 {'adult': False,
  'backdrop_path': '/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg',
  'genre_ids': [10751, 18],
  'id': 667257,
  'title': 'Impossible Things',
  'original_language': 'es',
  'original_title': 'Cosas imposibles',
  'overview': 'After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.',
  'popularity': 5.0882,
  'poster_path': '/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg',
  'release_date': '2021-06-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.395,
  'vote_count': 422},
 {'adult': False,
  'backdrop_path': '/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg',
  'genre_ids': [16, 28, 12, 878],
  'id': 324857,
  'title': 'Spider-Man: Into the Spider-Verse',
  'original_language': 'en',
  'original_title': 'Spider-Man: Into the Spider-Verse',
  'overview': 'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
  'popularity': 24.9928,
  'poster_path': '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
  'release_date': '2018-12-06',
  'softcore': False,
  'video': False,
  'vote_average': 8.393,
  'vote_count': 17238},
 {'adult': False,
  'backdrop_path': '/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg',
  'genre_ids': [12, 28, 878],
  'id': 1891,
  'title': 'The Empire Strikes Back',
  'original_language': 'en',
  'original_title': 'The Empire Strikes Back',
  'overview': 'The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.',
  'popularity': 17.2101,
  'poster_path': '/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg',
  'release_date': '1980-05-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.4,
  'vote_count': 18423},
 {'adult': False,
  'backdrop_path': '/nv5wwZou159v5OC61i4ElR7OqyY.jpg',
  'genre_ids': [14, 16, 12],
  'id': 4935,
  'title': "Howl's Moving Castle",
  'original_language': 'ja',
  'original_title': 'ハウルの動く城',
  'overview': 'Sophie, a young milliner, is turned into an elderly woman by a witch who enters her shop and curses her. She encounters a wizard named Howl and gets caught up in his resistance to fighting for the king.',
  'popularity': 21.1795,
  'poster_path': '/13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg',
  'release_date': '2004-09-09',
  'softcore': False,
  'video': False,
  'vote_average': 8.388,
  'vote_count': 11083},
 {'adult': False,
  'backdrop_path': '/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg',
  'genre_ids': [16, 18, 10749],
  'id': 378064,
  'title': 'A Silent Voice: The Movie',
  'original_language': 'ja',
  'original_title': '映画 聲の形',
  'overview': 'Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?',
  'popularity': 14.2294,
  'poster_path': '/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg',
  'release_date': '2016-09-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.387,
  'vote_count': 4491},
 {'adult': False,
  'backdrop_path': '/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg',
  'genre_ids': [80, 9648, 53],
  'id': 807,
  'title': 'Se7en',
  'original_language': 'en',
  'original_title': 'Se7en',
  'overview': 'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Somerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
  'popularity': 23.5084,
  'poster_path': '/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg',
  'release_date': '1995-09-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.382,
  'vote_count': 23098}]

# transforming it into a dataframe

In [5]:
pd.DataFrame(response.json()["results"])

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/gILte6Zd7m1YneIr6MVhh30S9pr.jpg,"[18, 80]",769,GoodFellas,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",23.8923,/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg,1990-09-12,False,False,8.500,14365
1,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,Seven Samurai,ja,七人の侍,A samurai answers a village's request for prot...,15.6686,/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg,1954-04-26,False,False,8.500,4233
2,False,/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg,"[16, 18, 10752]",12477,Grave of the Fireflies,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0128,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,False,False,8.400,6522
3,False,/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg,"[35, 18]",637,Life Is Beautiful,it,La vita è bella,A touching story of an Italian book seller of ...,13.8366,/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg,1997-12-20,False,False,8.439,13995
4,False,/xRyINp9KfMLVjRiO5nCsoRDdvvF.jpg,"[18, 53]",550,Fight Club,en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,30.9548,/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg,1999-10-15,False,False,8.438,32067
5,False,/a0lfia8tk8ifkrve0Tn8wkISUvs.jpg,"[12, 14, 28]",120,The Lord of the Rings: The Fellowship of the Ring,en,The Lord of the Rings: The Fellowship of the Ring,"Young hobbit Frodo Baggins, after inheriting a...",41.2906,/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg,2001-12-18,False,False,8.400,27585
6,False,/e3hG3uadtcP0pYdRa5ch4ysQW76.jpg,"[28, 18, 36]",14537,Harakiri,ja,切腹,Down-on-his-luck veteran Tsugumo Hanshirō ente...,10.0819,/3nPwMd3KviJWaHzG9fZCqlwWMas.jpg,1962-09-15,False,False,8.432,1210
7,False,/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg,"[18, 80]",598,City of God,pt,Cidade de Deus,In the poverty-stricken favelas of Rio de Jane...,12.4734,/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg,2002-08-30,False,False,8.429,8189
8,False,/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg,"[18, 10749]",11216,Cinema Paradiso,it,Nuovo Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",11.4261,/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg,1988-11-17,False,False,8.427,4828
9,False,/kWYfW2Re0rUDE6IHhy4CRuKWeFr.jpg,"[12, 14, 28]",121,The Lord of the Rings: The Two Towers,en,The Lord of the Rings: The Two Towers,Frodo Baggins and the other members of the Fel...,26.1014,/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg,2002-12-18,False,False,8.419,23906
10,False,/mufF1aYvwdpKerhq5R1YrVcbJLY.jpg,"[27, 53, 9648]",539,Psycho,en,Psycho,When larcenous real estate clerk Marion Crane ...,18.4761,/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg,1960-06-22,False,False,8.413,10994
11,False,/6Oa3zTiluBz2W8D2ou1MY16dUiF.jpg,[18],510,One Flew Over the Cuckoo's Nest,en,One Flew Over the Cuckoo's Nest,A petty criminal fakes insanity to serve his s...,13.7821,/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg,1975-11-19,False,False,8.413,11458
12,False,/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg,"[35, 18, 14, 10749]",40096,A Dog's Will,pt,O Auto da Compadecida,The lively João Grilo and the sly Chicó are po...,5.2383,/z9Au9XtK0ARzkKGsZCzMkmKgMPf.jpg,2000-09-15,False,False,8.400,1222
13,False,/4Nx40jwpoTHPjCWNGoaZ6kaoGxa.jpg,[18],255709,Hope,ko,소원,After 8-year-old So-won narrowly survives a br...,14.8548,/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg,2013-10-02,False,False,8.398,855
14,False,/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg,"[10751, 18]",667257,Impossible Things,es,Cosas imposibles,"After the death of her abusive husband, Matild...",5.0882,/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg,2021-06-17,False,False,8.395,422
15,False,/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg,"[16, 28, 12, 878]",324857,Spider-Man: Into the Spider-Verse,en,Spider-Man: Into the Spider-Verse,Struggling to find his place in the world whil...,24.9928,/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg,2018-12-06,False,False,8.393,17238
16,False,/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg,"[12, 28, 878]",1891,The Empire Strikes Back,en,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",17.2101,/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg,1980-05-20,False,False,8.400,18423
17,False,/nv5wwZou159v5OC61i4ElR7OqyY.jpg,"[14, 16, 12]",4935,Howl's Moving Castle,ja,ハウルの動く城,"Sophie, a young milliner, is turned into an el...",21.1795,/13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg,2004-09-09,False,False,8.388,11083
18,False,/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg,"[16, 18, 10749]",378064,A Silent Voice: The Movie,ja,映画 聲の形,Shouya Ishida starts bullying the new girl in ...,14.2294,/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg,2016-09-17,False,False,8.387,4491
19,False,/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg,"[80, 9648, 53]",807,Se7en,en,Se7en,Two homicide detectives are on a desperate hun...,23.5084,/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg,1995-09-22,False,False,8.382,23098

## only extracting needed columns

In [6]:
pd.DataFrame(response.json()["results"])[['id','title','adult','popularity','release_date','vote_average','vote_count']]

,id,title,adult,popularity,release_date,vote_average,vote_count
0,769,GoodFellas,False,23.8923,1990-09-12,8.500,14365
1,346,Seven Samurai,False,15.6686,1954-04-26,8.500,4233
2,12477,Grave of the Fireflies,False,0.0128,1988-04-16,8.400,6522
3,637,Life Is Beautiful,False,13.8366,1997-12-20,8.439,13995
4,550,Fight Club,False,30.9548,1999-10-15,8.438,32067
5,120,The Lord of the Rings: The Fellowship of the Ring,False,41.2906,2001-12-18,8.400,27585
6,14537,Harakiri,False,10.0819,1962-09-15,8.432,1210
7,598,City of God,False,12.4734,2002-08-30,8.429,8189
8,11216,Cinema Paradiso,False,11.4261,1988-11-17,8.427,4828
9,121,The Lord of the Rings: The Two Towers,False,26.1014,2002-12-18,8.419,23906
10,539,Psycho,False,18.4761,1960-06-22,8.413,10994
11,510,One Flew Over the Cuckoo's Nest,False,13.7821,1975-11-19,8.413,11458
12,40096,A Dog's Will,False,5.2383,2000-09-15,8.400,1222
13,255709,Hope,False,14.8548,2013-10-02,8.398,855
14,667257,Impossible Things,False,5.0882,2021-06-17,8.395,422
15,324857,Spider-Man: Into the Spider-Verse,False,24.9928,2018-12-06,8.393,17238
16,1891,The Empire Strikes Back,False,17.2101,1980-05-20,8.400,18423
17,4935,Howl's Moving Castle,False,21.1795,2004-09-09,8.388,11083
18,378064,A Silent Voice: The Movie,False,14.2294,2016-09-17,8.387,4491
19,807,Se7en,False,23.5084,1995-09-22,8.382,23098

In [7]:
df = pd.DataFrame() # empty dataset

### since the url has total 545 pages we have to iterate ovel all those urls(page=1, page =2...)

In [10]:
for i in range(1,546):
    print(i)
    response = requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key=f8223b6e16ffdbd7d7ccf3577a2c765a&page={i}")
    tempDf = pd.DataFrame(response.json()["results"])[['id','title','adult','popularity','release_date','vote_average','vote_count']]
    df = pd.concat([df, tempDf])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501

KeyError: 'results'

In [9]:
df

,id,title,adult,popularity,release_date,vote_average,vote_count
0,1007757,Swapped,False,228.4569,2026-05-01,8.978,1531
1,278,The Shawshank Redemption,False,75.6820,1994-09-23,8.700,30465
2,238,The Godfather,False,44.7992,1972-03-14,8.687,22978
3,687163,Project Hail Mary,False,263.7195,2026-03-15,8.648,4537
4,240,The Godfather Part II,False,28.9917,1974-12-20,8.571,13931
...,...,...,...,...,...,...,...
15,77338,The Intouchables,False,21.9558,2011-11-02,8.270,18432
16,652837,"Josee, the Tiger and the Fish",False,7.3657,2020-12-25,8.268,601
17,28,Apocalypse Now,False,13.7504,1979-05-19,8.268,9092
18,654299,Out of the Clear Blue Sky,False,3.4199,2019-12-24,8.263,384
19,1317149,I Swear,False,14.5776,2025-09-22,8.300,322

### finally u can convert to csv

In [ ]:
df.to_csv("movies.csv")